"""post

Revision ID: 2a97a32055ef
Revises: b46e3b6d6b62
Create Date: 2026-02-04 21:50:52.899721

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


#from alembic import op
#import sqlalchemy as sa
import sqlmodel # linha NOVA



# revision identifiers, used by Alembic.
revision: str = '2a97a32055ef'
down_revision: Union[str, Sequence[str], None] = 'b46e3b6d6b62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
